name: ROS2 Lint
on:
  pull_request:

jobs:
  ament_lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy
    strategy:
      fail-fast: false
      matrix:
          linter: [copyright, lint_cmake]
    steps:
    - uses: actions/checkout@v4
    - uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: humble
    - uses: ros-tooling/action-ros-lint@v0.1
      with:
        distribution: humble
        linter: ${{ matrix.linter }}
        package-name:
          ur_simulation_gazebo
